/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.adeo.offer.cluster.events.cluster.model.v2;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ClusterValidated extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3225560689253920419L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ClusterValidated\",\"namespace\":\"com.adeo.offer.cluster.events.cluster.model.v2\",\"fields\":[{\"name\":\"storeClusterIdentifier\",\"type\":\"int\",\"doc\":\"It is the unique identifier for a Store Cluster.\"},{\"name\":\"storeClusterName\",\"type\":\"string\",\"doc\":\"It is the name that is used to identify the Store Cluster.\"},{\"name\":\"storeClusterDescription\",\"type\":[\"null\",\"string\"],\"doc\":\"This description allows to describe the Store Cluster inside the Store Cluster Group with more details.\"},{\"name\":\"storeClusterOrdering\",\"type\":\"int\",\"doc\":\"It is the order of the Store Cluster inside the Store Cluster Group.\"},{\"name\":\"storeClusterCharacteristic\",\"type\":[\"null\",\"string\"],\"doc\":\"It is the characteristic of the Cluster inside the Cluster Group.\"},{\"name\":\"storeClusterCreationCollaboratorIdentifier\",\"type\":[\"null\",\"string\"],\"doc\":\"It is a code that is used to identify each collaborator in ADEO. In this case, it determines the collaborator at the origin of the creation of a Store Cluster.\"},{\"name\":\"storeClusterCreationDate\",\"type\":[\"null\",{\"type\":\"int\",\"logicalType\":\"date\"}],\"doc\":\"It is the creation date of the Store Cluster.\"},{\"name\":\"storeClusterValidationCollaboratorIdentifier\",\"type\":[\"null\",\"string\"],\"doc\":\"It is a code that is used to identify each collaborator in ADEO. In this case, it determines the collaborator at the origin of the validation of a Store Cluster.\"},{\"name\":\"storeClusterValidationDate\",\"type\":[\"null\",{\"type\":\"int\",\"logicalType\":\"date\"}],\"doc\":\"It is the validation date of the Store Cluster.\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();
static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.DateConversion());
  }

  private static final BinaryMessageEncoder<ClusterValidated> ENCODER =
      new BinaryMessageEncoder<ClusterValidated>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ClusterValidated> DECODER =
      new BinaryMessageDecoder<ClusterValidated>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ClusterValidated> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ClusterValidated> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ClusterValidated> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ClusterValidated>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ClusterValidated to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ClusterValidated from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ClusterValidated instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ClusterValidated fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** It is the unique identifier for a Store Cluster. */
  @Deprecated public int storeClusterIdentifier;
  /** It is the name that is used to identify the Store Cluster. */
  @Deprecated public java.lang.CharSequence storeClusterName;
  /** This description allows to describe the Store Cluster inside the Store Cluster Group with more details. */
  @Deprecated public java.lang.CharSequence storeClusterDescription;
  /** It is the order of the Store Cluster inside the Store Cluster Group. */
  @Deprecated public int storeClusterOrdering;
  /** It is the characteristic of the Cluster inside the Cluster Group. */
  @Deprecated public java.lang.CharSequence storeClusterCharacteristic;
  /** It is a code that is used to identify each collaborator in ADEO. In this case, it determines the collaborator at the origin of the creation of a Store Cluster. */
  @Deprecated public java.lang.CharSequence storeClusterCreationCollaboratorIdentifier;
  /** It is the creation date of the Store Cluster. */
  @Deprecated public java.time.LocalDate storeClusterCreationDate;
  /** It is a code that is used to identify each collaborator in ADEO. In this case, it determines the collaborator at the origin of the validation of a Store Cluster. */
  @Deprecated public java.lang.CharSequence storeClusterValidationCollaboratorIdentifier;
  /** It is the validation date of the Store Cluster. */
  @Deprecated public java.time.LocalDate storeClusterValidationDate;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ClusterValidated() {}

  /**
   * All-args constructor.
   * @param storeClusterIdentifier It is the unique identifier for a Store Cluster.
   * @param storeClusterName It is the name that is used to identify the Store Cluster.
   * @param storeClusterDescription This description allows to describe the Store Cluster inside the Store Cluster Group with more details.
   * @param storeClusterOrdering It is the order of the Store Cluster inside the Store Cluster Group.
   * @param storeClusterCharacteristic It is the characteristic of the Cluster inside the Cluster Group.
   * @param storeClusterCreationCollaboratorIdentifier It is a code that is used to identify each collaborator in ADEO. In this case, it determines the collaborator at the origin of the creation of a Store Cluster.
   * @param storeClusterCreationDate It is the creation date of the Store Cluster.
   * @param storeClusterValidationCollaboratorIdentifier It is a code that is used to identify each collaborator in ADEO. In this case, it determines the collaborator at the origin of the validation of a Store Cluster.
   * @param storeClusterValidationDate It is the validation date of the Store Cluster.
   */
  public ClusterValidated(java.lang.Integer storeClusterIdentifier, java.lang.CharSequence storeClusterName, java.lang.CharSequence storeClusterDescription, java.lang.Integer storeClusterOrdering, java.lang.CharSequence storeClusterCharacteristic, java.lang.CharSequence storeClusterCreationCollaboratorIdentifier, java.time.LocalDate storeClusterCreationDate, java.lang.CharSequence storeClusterValidationCollaboratorIdentifier, java.time.LocalDate storeClusterValidationDate) {
    this.storeClusterIdentifier = storeClusterIdentifier;
    this.storeClusterName = storeClusterName;
    this.storeClusterDescription = storeClusterDescription;
    this.storeClusterOrdering = storeClusterOrdering;
    this.storeClusterCharacteristic = storeClusterCharacteristic;
    this.storeClusterCreationCollaboratorIdentifier = storeClusterCreationCollaboratorIdentifier;
    this.storeClusterCreationDate = storeClusterCreationDate;
    this.storeClusterValidationCollaboratorIdentifier = storeClusterValidationCollaboratorIdentifier;
    this.storeClusterValidationDate = storeClusterValidationDate;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return storeClusterIdentifier;
    case 1: return storeClusterName;
    case 2: return storeClusterDescription;
    case 3: return storeClusterOrdering;
    case 4: return storeClusterCharacteristic;
    case 5: return storeClusterCreationCollaboratorIdentifier;
    case 6: return storeClusterCreationDate;
    case 7: return storeClusterValidationCollaboratorIdentifier;
    case 8: return storeClusterValidationDate;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: storeClusterIdentifier = (java.lang.Integer)value$; break;
    case 1: storeClusterName = (java.lang.CharSequence)value$; break;
    case 2: storeClusterDescription = (java.lang.CharSequence)value$; break;
    case 3: storeClusterOrdering = (java.lang.Integer)value$; break;
    case 4: storeClusterCharacteristic = (java.lang.CharSequence)value$; break;
    case 5: storeClusterCreationCollaboratorIdentifier = (java.lang.CharSequence)value$; break;
    case 6: storeClusterCreationDate = (java.time.LocalDate)value$; break;
    case 7: storeClusterValidationCollaboratorIdentifier = (java.lang.CharSequence)value$; break;
    case 8: storeClusterValidationDate = (java.time.LocalDate)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'storeClusterIdentifier' field.
   * @return It is the unique identifier for a Store Cluster.
   */
  public int getStoreClusterIdentifier() {
    return storeClusterIdentifier;
  }


  /**
   * Sets the value of the 'storeClusterIdentifier' field.
   * It is the unique identifier for a Store Cluster.
   * @param value the value to set.
   */
  public void setStoreClusterIdentifier(int value) {
    this.storeClusterIdentifier = value;
  }

  /**
   * Gets the value of the 'storeClusterName' field.
   * @return It is the name that is used to identify the Store Cluster.
   */
  public java.lang.CharSequence getStoreClusterName() {
    return storeClusterName;
  }


  /**
   * Sets the value of the 'storeClusterName' field.
   * It is the name that is used to identify the Store Cluster.
   * @param value the value to set.
   */
  public void setStoreClusterName(java.lang.CharSequence value) {
    this.storeClusterName = value;
  }

  /**
   * Gets the value of the 'storeClusterDescription' field.
   * @return This description allows to describe the Store Cluster inside the Store Cluster Group with more details.
   */
  public java.lang.CharSequence getStoreClusterDescription() {
    return storeClusterDescription;
  }


  /**
   * Sets the value of the 'storeClusterDescription' field.
   * This description allows to describe the Store Cluster inside the Store Cluster Group with more details.
   * @param value the value to set.
   */
  public void setStoreClusterDescription(java.lang.CharSequence value) {
    this.storeClusterDescription = value;
  }

  /**
   * Gets the value of the 'storeClusterOrdering' field.
   * @return It is the order of the Store Cluster inside the Store Cluster Group.
   */
  public int getStoreClusterOrdering() {
    return storeClusterOrdering;
  }


  /**
   * Sets the value of the 'storeClusterOrdering' field.
   * It is the order of the Store Cluster inside the Store Cluster Group.
   * @param value the value to set.
   */
  public void setStoreClusterOrdering(int value) {
    this.storeClusterOrdering = value;
  }

  /**
   * Gets the value of the 'storeClusterCharacteristic' field.
   * @return It is the characteristic of the Cluster inside the Cluster Group.
   */
  public java.lang.CharSequence getStoreClusterCharacteristic() {
    return storeClusterCharacteristic;
  }


  /**
   * Sets the value of the 'storeClusterCharacteristic' field.
   * It is the characteristic of the Cluster inside the Cluster Group.
   * @param value the value to set.
   */
  public void setStoreClusterCharacteristic(java.lang.CharSequence value) {
    this.storeClusterCharacteristic = value;
  }

  /**
   * Gets the value of the 'storeClusterCreationCollaboratorIdentifier' field.
   * @return It is a code that is used to identify each collaborator in ADEO. In this case, it determines the collaborator at the origin of the creation of a Store Cluster.
   */
  public java.lang.CharSequence getStoreClusterCreationCollaboratorIdentifier() {
    return storeClusterCreationCollaboratorIdentifier;
  }


  /**
   * Sets the value of the 'storeClusterCreationCollaboratorIdentifier' field.
   * It is a code that is used to identify each collaborator in ADEO. In this case, it determines the collaborator at the origin of the creation of a Store Cluster.
   * @param value the value to set.
   */
  public void setStoreClusterCreationCollaboratorIdentifier(java.lang.CharSequence value) {
    this.storeClusterCreationCollaboratorIdentifier = value;
  }

  /**
   * Gets the value of the 'storeClusterCreationDate' field.
   * @return It is the creation date of the Store Cluster.
   */
  public java.time.LocalDate getStoreClusterCreationDate() {
    return storeClusterCreationDate;
  }


  /**
   * Sets the value of the 'storeClusterCreationDate' field.
   * It is the creation date of the Store Cluster.
   * @param value the value to set.
   */
  public void setStoreClusterCreationDate(java.time.LocalDate value) {
    this.storeClusterCreationDate = value;
  }

  /**
   * Gets the value of the 'storeClusterValidationCollaboratorIdentifier' field.
   * @return It is a code that is used to identify each collaborator in ADEO. In this case, it determines the collaborator at the origin of the validation of a Store Cluster.
   */
  public java.lang.CharSequence getStoreClusterValidationCollaboratorIdentifier() {
    return storeClusterValidationCollaboratorIdentifier;
  }


  /**
   * Sets the value of the 'storeClusterValidationCollaboratorIdentifier' field.
   * It is a code that is used to identify each collaborator in ADEO. In this case, it determines the collaborator at the origin of the validation of a Store Cluster.
   * @param value the value to set.
   */
  public void setStoreClusterValidationCollaboratorIdentifier(java.lang.CharSequence value) {
    this.storeClusterValidationCollaboratorIdentifier = value;
  }

  /**
   * Gets the value of the 'storeClusterValidationDate' field.
   * @return It is the validation date of the Store Cluster.
   */
  public java.time.LocalDate getStoreClusterValidationDate() {
    return storeClusterValidationDate;
  }


  /**
   * Sets the value of the 'storeClusterValidationDate' field.
   * It is the validation date of the Store Cluster.
   * @param value the value to set.
   */
  public void setStoreClusterValidationDate(java.time.LocalDate value) {
    this.storeClusterValidationDate = value;
  }

  /**
   * Creates a new ClusterValidated RecordBuilder.
   * @return A new ClusterValidated RecordBuilder
   */
  public static com.adeo.offer.cluster.events.cluster.model.v2.ClusterValidated.Builder newBuilder() {
    return new com.adeo.offer.cluster.events.cluster.model.v2.ClusterValidated.Builder();
  }

  /**
   * Creates a new ClusterValidated RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ClusterValidated RecordBuilder
   */
  public static com.adeo.offer.cluster.events.cluster.model.v2.ClusterValidated.Builder newBuilder(com.adeo.offer.cluster.events.cluster.model.v2.ClusterValidated.Builder other) {
    if (other == null) {
      return new com.adeo.offer.cluster.events.cluster.model.v2.ClusterValidated.Builder();
    } else {
      return new com.adeo.offer.cluster.events.cluster.model.v2.ClusterValidated.Builder(other);
    }
  }

  /**
   * Creates a new ClusterValidated RecordBuilder by copying an existing ClusterValidated instance.
   * @param other The existing instance to copy.
   * @return A new ClusterValidated RecordBuilder
   */
  public static com.adeo.offer.cluster.events.cluster.model.v2.ClusterValidated.Builder newBuilder(com.adeo.offer.cluster.events.cluster.model.v2.ClusterValidated other) {
    if (other == null) {
      return new com.adeo.offer.cluster.events.cluster.model.v2.ClusterValidated.Builder();
    } else {
      return new com.adeo.offer.cluster.events.cluster.model.v2.ClusterValidated.Builder(other);
    }
  }

  /**
   * RecordBuilder for ClusterValidated instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ClusterValidated>
    implements org.apache.avro.data.RecordBuilder<ClusterValidated> {

    /** It is the unique identifier for a Store Cluster. */
    private int storeClusterIdentifier;
    /** It is the name that is used to identify the Store Cluster. */
    private java.lang.CharSequence storeClusterName;
    /** This description allows to describe the Store Cluster inside the Store Cluster Group with more details. */
    private java.lang.CharSequence storeClusterDescription;
    /** It is the order of the Store Cluster inside the Store Cluster Group. */
    private int storeClusterOrdering;
    /** It is the characteristic of the Cluster inside the Cluster Group. */
    private java.lang.CharSequence storeClusterCharacteristic;
    /** It is a code that is used to identify each collaborator in ADEO. In this case, it determines the collaborator at the origin of the creation of a Store Cluster. */
    private java.lang.CharSequence storeClusterCreationCollaboratorIdentifier;
    /** It is the creation date of the Store Cluster. */
    private java.time.LocalDate storeClusterCreationDate;
    /** It is a code that is used to identify each collaborator in ADEO. In this case, it determines the collaborator at the origin of the validation of a Store Cluster. */
    private java.lang.CharSequence storeClusterValidationCollaboratorIdentifier;
    /** It is the validation date of the Store Cluster. */
    private java.time.LocalDate storeClusterValidationDate;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.adeo.offer.cluster.events.cluster.model.v2.ClusterValidated.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.storeClusterIdentifier)) {
        this.storeClusterIdentifier = data().deepCopy(fields()[0].schema(), other.storeClusterIdentifier);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.storeClusterName)) {
        this.storeClusterName = data().deepCopy(fields()[1].schema(), other.storeClusterName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.storeClusterDescription)) {
        this.storeClusterDescription = data().deepCopy(fields()[2].schema(), other.storeClusterDescription);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.storeClusterOrdering)) {
        this.storeClusterOrdering = data().deepCopy(fields()[3].schema(), other.storeClusterOrdering);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.storeClusterCharacteristic)) {
        this.storeClusterCharacteristic = data().deepCopy(fields()[4].schema(), other.storeClusterCharacteristic);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.storeClusterCreationCollaboratorIdentifier)) {
        this.storeClusterCreationCollaboratorIdentifier = data().deepCopy(fields()[5].schema(), other.storeClusterCreationCollaboratorIdentifier);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.storeClusterCreationDate)) {
        this.storeClusterCreationDate = data().deepCopy(fields()[6].schema(), other.storeClusterCreationDate);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.storeClusterValidationCollaboratorIdentifier)) {
        this.storeClusterValidationCollaboratorIdentifier = data().deepCopy(fields()[7].schema(), other.storeClusterValidationCollaboratorIdentifier);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.storeClusterValidationDate)) {
        this.storeClusterValidationDate = data().deepCopy(fields()[8].schema(), other.storeClusterValidationDate);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
    }

    /**
     * Creates a Builder by copying an existing ClusterValidated instance
     * @param other The existing instance to copy.
     */
    private Builder(com.adeo.offer.cluster.events.cluster.model.v2.ClusterValidated other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.storeClusterIdentifier)) {
        this.storeClusterIdentifier = data().deepCopy(fields()[0].schema(), other.storeClusterIdentifier);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.storeClusterName)) {
        this.storeClusterName = data().deepCopy(fields()[1].schema(), other.storeClusterName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.storeClusterDescription)) {
        this.storeClusterDescription = data().deepCopy(fields()[2].schema(), other.storeClusterDescription);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.storeClusterOrdering)) {
        this.storeClusterOrdering = data().deepCopy(fields()[3].schema(), other.storeClusterOrdering);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.storeClusterCharacteristic)) {
        this.storeClusterCharacteristic = data().deepCopy(fields()[4].schema(), other.storeClusterCharacteristic);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.storeClusterCreationCollaboratorIdentifier)) {
        this.storeClusterCreationCollaboratorIdentifier = data().deepCopy(fields()[5].schema(), other.storeClusterCreationCollaboratorIdentifier);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.storeClusterCreationDate)) {
        this.storeClusterCreationDate = data().deepCopy(fields()[6].schema(), other.storeClusterCreationDate);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.storeClusterValidationCollaboratorIdentifier)) {
        this.storeClusterValidationCollaboratorIdentifier = data().deepCopy(fields()[7].schema(), other.storeClusterValidationCollaboratorIdentifier);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.storeClusterValidationDate)) {
        this.storeClusterValidationDate = data().deepCopy(fields()[8].schema(), other.storeClusterValidationDate);
        fieldSetFlags()[8] = true;
      }
    }

    /**
      * Gets the value of the 'storeClusterIdentifier' field.
      * It is the unique identifier for a Store Cluster.
      * @return The value.
      */
    public int getStoreClusterIdentifier() {
      return storeClusterIdentifier;
    }


    /**
      * Sets the value of the 'storeClusterIdentifier' field.
      * It is the unique identifier for a Store Cluster.
      * @param value The value of 'storeClusterIdentifier'.
      * @return This builder.
      */
    public com.adeo.offer.cluster.events.cluster.model.v2.ClusterValidated.Builder setStoreClusterIdentifier(int value) {
      validate(fields()[0], value);
      this.storeClusterIdentifier = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'storeClusterIdentifier' field has been set.
      * It is the unique identifier for a Store Cluster.
      * @return True if the 'storeClusterIdentifier' field has been set, false otherwise.
      */
    public boolean hasStoreClusterIdentifier() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'storeClusterIdentifier' field.
      * It is the unique identifier for a Store Cluster.
      * @return This builder.
      */
    public com.adeo.offer.cluster.events.cluster.model.v2.ClusterValidated.Builder clearStoreClusterIdentifier() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'storeClusterName' field.
      * It is the name that is used to identify the Store Cluster.
      * @return The value.
      */
    public java.lang.CharSequence getStoreClusterName() {
      return storeClusterName;
    }


    /**
      * Sets the value of the 'storeClusterName' field.
      * It is the name that is used to identify the Store Cluster.
      * @param value The value of 'storeClusterName'.
      * @return This builder.
      */
    public com.adeo.offer.cluster.events.cluster.model.v2.ClusterValidated.Builder setStoreClusterName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.storeClusterName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'storeClusterName' field has been set.
      * It is the name that is used to identify the Store Cluster.
      * @return True if the 'storeClusterName' field has been set, false otherwise.
      */
    public boolean hasStoreClusterName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'storeClusterName' field.
      * It is the name that is used to identify the Store Cluster.
      * @return This builder.
      */
    public com.adeo.offer.cluster.events.cluster.model.v2.ClusterValidated.Builder clearStoreClusterName() {
      storeClusterName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'storeClusterDescription' field.
      * This description allows to describe the Store Cluster inside the Store Cluster Group with more details.
      * @return The value.
      */
    public java.lang.CharSequence getStoreClusterDescription() {
      return storeClusterDescription;
    }


    /**
      * Sets the value of the 'storeClusterDescription' field.
      * This description allows to describe the Store Cluster inside the Store Cluster Group with more details.
      * @param value The value of 'storeClusterDescription'.
      * @return This builder.
      */
    public com.adeo.offer.cluster.events.cluster.model.v2.ClusterValidated.Builder setStoreClusterDescription(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.storeClusterDescription = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'storeClusterDescription' field has been set.
      * This description allows to describe the Store Cluster inside the Store Cluster Group with more details.
      * @return True if the 'storeClusterDescription' field has been set, false otherwise.
      */
    public boolean hasStoreClusterDescription() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'storeClusterDescription' field.
      * This description allows to describe the Store Cluster inside the Store Cluster Group with more details.
      * @return This builder.
      */
    public com.adeo.offer.cluster.events.cluster.model.v2.ClusterValidated.Builder clearStoreClusterDescription() {
      storeClusterDescription = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'storeClusterOrdering' field.
      * It is the order of the Store Cluster inside the Store Cluster Group.
      * @return The value.
      */
    public int getStoreClusterOrdering() {
      return storeClusterOrdering;
    }


    /**
      * Sets the value of the 'storeClusterOrdering' field.
      * It is the order of the Store Cluster inside the Store Cluster Group.
      * @param value The value of 'storeClusterOrdering'.
      * @return This builder.
      */
    public com.adeo.offer.cluster.events.cluster.model.v2.ClusterValidated.Builder setStoreClusterOrdering(int value) {
      validate(fields()[3], value);
      this.storeClusterOrdering = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'storeClusterOrdering' field has been set.
      * It is the order of the Store Cluster inside the Store Cluster Group.
      * @return True if the 'storeClusterOrdering' field has been set, false otherwise.
      */
    public boolean hasStoreClusterOrdering() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'storeClusterOrdering' field.
      * It is the order of the Store Cluster inside the Store Cluster Group.
      * @return This builder.
      */
    public com.adeo.offer.cluster.events.cluster.model.v2.ClusterValidated.Builder clearStoreClusterOrdering() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'storeClusterCharacteristic' field.
      * It is the characteristic of the Cluster inside the Cluster Group.
      * @return The value.
      */
    public java.lang.CharSequence getStoreClusterCharacteristic() {
      return storeClusterCharacteristic;
    }


    /**
      * Sets the value of the 'storeClusterCharacteristic' field.
      * It is the characteristic of the Cluster inside the Cluster Group.
      * @param value The value of 'storeClusterCharacteristic'.
      * @return This builder.
      */
    public com.adeo.offer.cluster.events.cluster.model.v2.ClusterValidated.Builder setStoreClusterCharacteristic(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.storeClusterCharacteristic = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'storeClusterCharacteristic' field has been set.
      * It is the characteristic of the Cluster inside the Cluster Group.
      * @return True if the 'storeClusterCharacteristic' field has been set, false otherwise.
      */
    public boolean hasStoreClusterCharacteristic() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'storeClusterCharacteristic' field.
      * It is the characteristic of the Cluster inside the Cluster Group.
      * @return This builder.
      */
    public com.adeo.offer.cluster.events.cluster.model.v2.ClusterValidated.Builder clearStoreClusterCharacteristic() {
      storeClusterCharacteristic = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'storeClusterCreationCollaboratorIdentifier' field.
      * It is a code that is used to identify each collaborator in ADEO. In this case, it determines the collaborator at the origin of the creation of a Store Cluster.
      * @return The value.
      */
    public java.lang.CharSequence getStoreClusterCreationCollaboratorIdentifier() {
      return storeClusterCreationCollaboratorIdentifier;
    }


    /**
      * Sets the value of the 'storeClusterCreationCollaboratorIdentifier' field.
      * It is a code that is used to identify each collaborator in ADEO. In this case, it determines the collaborator at the origin of the creation of a Store Cluster.
      * @param value The value of 'storeClusterCreationCollaboratorIdentifier'.
      * @return This builder.
      */
    public com.adeo.offer.cluster.events.cluster.model.v2.ClusterValidated.Builder setStoreClusterCreationCollaboratorIdentifier(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.storeClusterCreationCollaboratorIdentifier = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'storeClusterCreationCollaboratorIdentifier' field has been set.
      * It is a code that is used to identify each collaborator in ADEO. In this case, it determines the collaborator at the origin of the creation of a Store Cluster.
      * @return True if the 'storeClusterCreationCollaboratorIdentifier' field has been set, false otherwise.
      */
    public boolean hasStoreClusterCreationCollaboratorIdentifier() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'storeClusterCreationCollaboratorIdentifier' field.
      * It is a code that is used to identify each collaborator in ADEO. In this case, it determines the collaborator at the origin of the creation of a Store Cluster.
      * @return This builder.
      */
    public com.adeo.offer.cluster.events.cluster.model.v2.ClusterValidated.Builder clearStoreClusterCreationCollaboratorIdentifier() {
      storeClusterCreationCollaboratorIdentifier = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'storeClusterCreationDate' field.
      * It is the creation date of the Store Cluster.
      * @return The value.
      */
    public java.time.LocalDate getStoreClusterCreationDate() {
      return storeClusterCreationDate;
    }


    /**
      * Sets the value of the 'storeClusterCreationDate' field.
      * It is the creation date of the Store Cluster.
      * @param value The value of 'storeClusterCreationDate'.
      * @return This builder.
      */
    public com.adeo.offer.cluster.events.cluster.model.v2.ClusterValidated.Builder setStoreClusterCreationDate(java.time.LocalDate value) {
      validate(fields()[6], value);
      this.storeClusterCreationDate = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'storeClusterCreationDate' field has been set.
      * It is the creation date of the Store Cluster.
      * @return True if the 'storeClusterCreationDate' field has been set, false otherwise.
      */
    public boolean hasStoreClusterCreationDate() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'storeClusterCreationDate' field.
      * It is the creation date of the Store Cluster.
      * @return This builder.
      */
    public com.adeo.offer.cluster.events.cluster.model.v2.ClusterValidated.Builder clearStoreClusterCreationDate() {
      storeClusterCreationDate = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'storeClusterValidationCollaboratorIdentifier' field.
      * It is a code that is used to identify each collaborator in ADEO. In this case, it determines the collaborator at the origin of the validation of a Store Cluster.
      * @return The value.
      */
    public java.lang.CharSequence getStoreClusterValidationCollaboratorIdentifier() {
      return storeClusterValidationCollaboratorIdentifier;
    }


    /**
      * Sets the value of the 'storeClusterValidationCollaboratorIdentifier' field.
      * It is a code that is used to identify each collaborator in ADEO. In this case, it determines the collaborator at the origin of the validation of a Store Cluster.
      * @param value The value of 'storeClusterValidationCollaboratorIdentifier'.
      * @return This builder.
      */
    public com.adeo.offer.cluster.events.cluster.model.v2.ClusterValidated.Builder setStoreClusterValidationCollaboratorIdentifier(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.storeClusterValidationCollaboratorIdentifier = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'storeClusterValidationCollaboratorIdentifier' field has been set.
      * It is a code that is used to identify each collaborator in ADEO. In this case, it determines the collaborator at the origin of the validation of a Store Cluster.
      * @return True if the 'storeClusterValidationCollaboratorIdentifier' field has been set, false otherwise.
      */
    public boolean hasStoreClusterValidationCollaboratorIdentifier() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'storeClusterValidationCollaboratorIdentifier' field.
      * It is a code that is used to identify each collaborator in ADEO. In this case, it determines the collaborator at the origin of the validation of a Store Cluster.
      * @return This builder.
      */
    public com.adeo.offer.cluster.events.cluster.model.v2.ClusterValidated.Builder clearStoreClusterValidationCollaboratorIdentifier() {
      storeClusterValidationCollaboratorIdentifier = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'storeClusterValidationDate' field.
      * It is the validation date of the Store Cluster.
      * @return The value.
      */
    public java.time.LocalDate getStoreClusterValidationDate() {
      return storeClusterValidationDate;
    }


    /**
      * Sets the value of the 'storeClusterValidationDate' field.
      * It is the validation date of the Store Cluster.
      * @param value The value of 'storeClusterValidationDate'.
      * @return This builder.
      */
    public com.adeo.offer.cluster.events.cluster.model.v2.ClusterValidated.Builder setStoreClusterValidationDate(java.time.LocalDate value) {
      validate(fields()[8], value);
      this.storeClusterValidationDate = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'storeClusterValidationDate' field has been set.
      * It is the validation date of the Store Cluster.
      * @return True if the 'storeClusterValidationDate' field has been set, false otherwise.
      */
    public boolean hasStoreClusterValidationDate() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'storeClusterValidationDate' field.
      * It is the validation date of the Store Cluster.
      * @return This builder.
      */
    public com.adeo.offer.cluster.events.cluster.model.v2.ClusterValidated.Builder clearStoreClusterValidationDate() {
      storeClusterValidationDate = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ClusterValidated build() {
      try {
        ClusterValidated record = new ClusterValidated();
        record.storeClusterIdentifier = fieldSetFlags()[0] ? this.storeClusterIdentifier : (java.lang.Integer) defaultValue(fields()[0]);
        record.storeClusterName = fieldSetFlags()[1] ? this.storeClusterName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.storeClusterDescription = fieldSetFlags()[2] ? this.storeClusterDescription : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.storeClusterOrdering = fieldSetFlags()[3] ? this.storeClusterOrdering : (java.lang.Integer) defaultValue(fields()[3]);
        record.storeClusterCharacteristic = fieldSetFlags()[4] ? this.storeClusterCharacteristic : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.storeClusterCreationCollaboratorIdentifier = fieldSetFlags()[5] ? this.storeClusterCreationCollaboratorIdentifier : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.storeClusterCreationDate = fieldSetFlags()[6] ? this.storeClusterCreationDate : (java.time.LocalDate) defaultValue(fields()[6]);
        record.storeClusterValidationCollaboratorIdentifier = fieldSetFlags()[7] ? this.storeClusterValidationCollaboratorIdentifier : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.storeClusterValidationDate = fieldSetFlags()[8] ? this.storeClusterValidationDate : (java.time.LocalDate) defaultValue(fields()[8]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ClusterValidated>
    WRITER$ = (org.apache.avro.io.DatumWriter<ClusterValidated>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ClusterValidated>
    READER$ = (org.apache.avro.io.DatumReader<ClusterValidated>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










