/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.adeo.offer.cluster.events.cluster.model.v2;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class StoreClusterGroupValidatedKey extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7397702318620368106L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"StoreClusterGroupValidatedKey\",\"namespace\":\"com.adeo.offer.cluster.events.cluster.model.v2\",\"fields\":[{\"name\":\"storeClusterGroupIdentifier\",\"type\":\"int\",\"doc\":\"It is the unique identifier for a Store Cluster Group.\"}],\"version\":1}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<StoreClusterGroupValidatedKey> ENCODER =
      new BinaryMessageEncoder<StoreClusterGroupValidatedKey>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<StoreClusterGroupValidatedKey> DECODER =
      new BinaryMessageDecoder<StoreClusterGroupValidatedKey>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<StoreClusterGroupValidatedKey> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<StoreClusterGroupValidatedKey> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<StoreClusterGroupValidatedKey> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<StoreClusterGroupValidatedKey>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this StoreClusterGroupValidatedKey to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a StoreClusterGroupValidatedKey from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a StoreClusterGroupValidatedKey instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static StoreClusterGroupValidatedKey fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** It is the unique identifier for a Store Cluster Group. */
  @Deprecated public int storeClusterGroupIdentifier;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public StoreClusterGroupValidatedKey() {}

  /**
   * All-args constructor.
   * @param storeClusterGroupIdentifier It is the unique identifier for a Store Cluster Group.
   */
  public StoreClusterGroupValidatedKey(java.lang.Integer storeClusterGroupIdentifier) {
    this.storeClusterGroupIdentifier = storeClusterGroupIdentifier;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return storeClusterGroupIdentifier;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: storeClusterGroupIdentifier = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'storeClusterGroupIdentifier' field.
   * @return It is the unique identifier for a Store Cluster Group.
   */
  public int getStoreClusterGroupIdentifier() {
    return storeClusterGroupIdentifier;
  }


  /**
   * Sets the value of the 'storeClusterGroupIdentifier' field.
   * It is the unique identifier for a Store Cluster Group.
   * @param value the value to set.
   */
  public void setStoreClusterGroupIdentifier(int value) {
    this.storeClusterGroupIdentifier = value;
  }

  /**
   * Creates a new StoreClusterGroupValidatedKey RecordBuilder.
   * @return A new StoreClusterGroupValidatedKey RecordBuilder
   */
  public static com.adeo.offer.cluster.events.cluster.model.v2.StoreClusterGroupValidatedKey.Builder newBuilder() {
    return new com.adeo.offer.cluster.events.cluster.model.v2.StoreClusterGroupValidatedKey.Builder();
  }

  /**
   * Creates a new StoreClusterGroupValidatedKey RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new StoreClusterGroupValidatedKey RecordBuilder
   */
  public static com.adeo.offer.cluster.events.cluster.model.v2.StoreClusterGroupValidatedKey.Builder newBuilder(com.adeo.offer.cluster.events.cluster.model.v2.StoreClusterGroupValidatedKey.Builder other) {
    if (other == null) {
      return new com.adeo.offer.cluster.events.cluster.model.v2.StoreClusterGroupValidatedKey.Builder();
    } else {
      return new com.adeo.offer.cluster.events.cluster.model.v2.StoreClusterGroupValidatedKey.Builder(other);
    }
  }

  /**
   * Creates a new StoreClusterGroupValidatedKey RecordBuilder by copying an existing StoreClusterGroupValidatedKey instance.
   * @param other The existing instance to copy.
   * @return A new StoreClusterGroupValidatedKey RecordBuilder
   */
  public static com.adeo.offer.cluster.events.cluster.model.v2.StoreClusterGroupValidatedKey.Builder newBuilder(com.adeo.offer.cluster.events.cluster.model.v2.StoreClusterGroupValidatedKey other) {
    if (other == null) {
      return new com.adeo.offer.cluster.events.cluster.model.v2.StoreClusterGroupValidatedKey.Builder();
    } else {
      return new com.adeo.offer.cluster.events.cluster.model.v2.StoreClusterGroupValidatedKey.Builder(other);
    }
  }

  /**
   * RecordBuilder for StoreClusterGroupValidatedKey instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<StoreClusterGroupValidatedKey>
    implements org.apache.avro.data.RecordBuilder<StoreClusterGroupValidatedKey> {

    /** It is the unique identifier for a Store Cluster Group. */
    private int storeClusterGroupIdentifier;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.adeo.offer.cluster.events.cluster.model.v2.StoreClusterGroupValidatedKey.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.storeClusterGroupIdentifier)) {
        this.storeClusterGroupIdentifier = data().deepCopy(fields()[0].schema(), other.storeClusterGroupIdentifier);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing StoreClusterGroupValidatedKey instance
     * @param other The existing instance to copy.
     */
    private Builder(com.adeo.offer.cluster.events.cluster.model.v2.StoreClusterGroupValidatedKey other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.storeClusterGroupIdentifier)) {
        this.storeClusterGroupIdentifier = data().deepCopy(fields()[0].schema(), other.storeClusterGroupIdentifier);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'storeClusterGroupIdentifier' field.
      * It is the unique identifier for a Store Cluster Group.
      * @return The value.
      */
    public int getStoreClusterGroupIdentifier() {
      return storeClusterGroupIdentifier;
    }


    /**
      * Sets the value of the 'storeClusterGroupIdentifier' field.
      * It is the unique identifier for a Store Cluster Group.
      * @param value The value of 'storeClusterGroupIdentifier'.
      * @return This builder.
      */
    public com.adeo.offer.cluster.events.cluster.model.v2.StoreClusterGroupValidatedKey.Builder setStoreClusterGroupIdentifier(int value) {
      validate(fields()[0], value);
      this.storeClusterGroupIdentifier = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'storeClusterGroupIdentifier' field has been set.
      * It is the unique identifier for a Store Cluster Group.
      * @return True if the 'storeClusterGroupIdentifier' field has been set, false otherwise.
      */
    public boolean hasStoreClusterGroupIdentifier() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'storeClusterGroupIdentifier' field.
      * It is the unique identifier for a Store Cluster Group.
      * @return This builder.
      */
    public com.adeo.offer.cluster.events.cluster.model.v2.StoreClusterGroupValidatedKey.Builder clearStoreClusterGroupIdentifier() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public StoreClusterGroupValidatedKey build() {
      try {
        StoreClusterGroupValidatedKey record = new StoreClusterGroupValidatedKey();
        record.storeClusterGroupIdentifier = fieldSetFlags()[0] ? this.storeClusterGroupIdentifier : (java.lang.Integer) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<StoreClusterGroupValidatedKey>
    WRITER$ = (org.apache.avro.io.DatumWriter<StoreClusterGroupValidatedKey>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<StoreClusterGroupValidatedKey>
    READER$ = (org.apache.avro.io.DatumReader<StoreClusterGroupValidatedKey>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.storeClusterGroupIdentifier);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.storeClusterGroupIdentifier = in.readInt();

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.storeClusterGroupIdentifier = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










